### ISSUE TITLE
"Missing Title" Error on Background

### ISSUE THREAD

**Issue by aetherealtech** [reqnroll/Reqnroll.Rider#43]
The plugin will flag an error in a feature file, "Missing Title", on a background under a rule that is preceded by a comment.

Minimally reproducing example:

```
Feature: Some Feature

    Rule: Some Rule

        # A Comment

        Background:
```

No errors are reported in the Visual Studio plugin, and no issues occur during building or running the tests.  It just causes the project to be flagged as having an error in Rider.
